- name: Deploy projects_rev02 
  hosts: molecule
  roles:
    - docker_compose
  vars:
    docker_compose__projects:
      - name: mosquitto
        files_directory: ./files/projects_rev02/mosquitto
      - name: nginx
        files_directory: ./files/projects_rev02/nginx
      - name: nodejs
        files_directory: ./files/projects_rev02/nodejs
