dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  - name: molecule-docker-compose-role-dind
    image: dind-molecule-docker-compose-role
scenario:
  converge_sequence:
    - dependency
    - create
    - prepare
    - side_effect side_effect_projects_rev01.yml
    - converge
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - side_effect side_effect_projects_rev01.yml
    - converge
    - verify
    - cleanup
    - destroy
